# XAgent configuration for L3AGI integration
xagent:
  mode: "auto"
  model:
    name: "gpt-4"
    temperature: 0.1
    max_tokens: 2000
  
  tools:
    - name: "web_search"
      enabled: true
    - name: "code_execution"
      enabled: true
    - name: "file_operation"
      enabled: true
  
  constraints:
    max_iterations: 5
    timeout: 300
  
  logging:
    level: "INFO"
    save_log: true
    log_dir: "./logs"